---
title: "Did Toronto’s Neighbourhood Improvement Areas Curb Crime?"
subtitle: "An Analysis of Crime Reduction from 2014 to 2023"
author: 
  - Harsh M Pareek
thanks: "Code and data are available at: https://github.com/HarshMPareek/Project1"
date: today
date-format: long
abstract: "This paper explores whether the designation of Neighbourhood Improvement Areas (NIA) in Toronto has been effective in reducing crime rates from 2014 to 2023. Using crime data across multiple categories, such as assault, robbery, and bike theft, I aim to correlate the impact of NIA designation with changes in crime trends."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

In 2014, the City of Toronto designated 31 areas as Neighbourhood Improvement Areas (NIAs) under the Toronto Strong Neighbourhoods Strategy 2020 (TSNS2020). This initiative aimed to enhance the social and economic conditions in under-served neighborhoods by providing targeted resources. While the broader objectives of TSNS2020 encompass overall community development, this paper specifically examines the initiative’s impact on various crime rates, including assault, robbery, bike theft, break and enter, homicide, shooting, theft from motor vehicles, and theft over $5000.

This analysis uses crime data from 2014 to 2023, obtained from Open Data Toronto, to assess changes in these crime rates within the designated NIAs. The purpose is to evaluate whether the intervention has led to measurable decreases in these specific crime categories, thereby contributing to the overall safety and security of the residents.

The paper is structured to first describe the dataset and statistical methods applied in the analysis (see @sec-data), followed by a presentation of the results. The discussion section (@sec-discussion) will interpret the significance of these findings in the context of policy effectiveness and community safety. Finally, the paper will conclude with recommendations for future urban policy based on the observed data trends.



# Data {#sec-data}

Some of our data is of penguins (@fig-bills), from @palmerpenguins.


Talk more about it.

And also planes (@fig-planes). (You can change the height and width, but don't worry about doing that until you have finished every other aspect of the paper - Quarto will try to make it look nice and the defaults usually work well once you have enough text.)



Talk way more about it. 



# Model

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in [Appendix -@sec-model-details].

## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_i$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters.  

\begin{align} 
y_i|\mu_i, \sigma &\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_i + \gamma_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\sigma &\sim \mbox{Exponential}(1)
\end{align}

We run the model in R [@citeR] using the `rstanarm` package of @rstanarm. We use the default priors from `rstanarm`.


### Model justification

We expect a positive relationship between the size of the wings and time spent aloft. In particular...

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results

Our results are summarized in @tbl-modelresults.





# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check

In @fig-ppcheckandposteriorvsprior-1 we implement a posterior predictive check. This shows...

In @fig-ppcheckandposteriorvsprior-2 we compare the posterior with the prior. This shows... 



## Diagnostics

@fig-stanareyouokay-1 is a trace plot. It shows... This suggests...

@fig-stanareyouokay-2 is a Rhat plot. It shows... This suggests...





\newpage


# References


